# Generated by Django 2.0.6 on 2019-03-17 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('foreignkeyToUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(default='', max_length=200)),
                ('itemText', models.TextField(max_length=5000)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('optionalPostImage', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(default='', max_length=200)),
                ('postText', models.TextField(max_length=5000)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('optionalPostImage', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('foreignkeyToAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project2App.AuthorModel')),
            ],
        ),
        migrations.AddField(
            model_name='relatedmodel',
            name='foreignKeyToWikiPosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project2App.WikiPostsModel'),
        ),
    ]
